Fixed HolographicSpatialStage build errors
SpatialStageManager.cpp(20,95): error C2065: '_1': undeclared identifier
SpatialStageManager.cpp(146,26): error C2398: Element '1': conversion from 'double' to 'float' requires a narrowing conversion